# Generated by Django 5.2.8 on 2026-09-13 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_videocomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="VideoLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_likes",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("video", "ip_hash"),
                        name="unique_video_like_per_visitor",
                    )
                ],
            },
        ),
    ]
