# Generated by Django 5.2.8 on 2026-09-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_video_likes_videolike"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="is_short",
            field=models.BooleanField(
                default=False, verbose_name="Short/Reel वीडियो है"
            ),
        ),
    ]
