# Generated by Django 5.2.8 on 2026-09-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liveblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveblog",
            name="youtube_live_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube video/live URL to embed above the timeline while this is live (any youtube.com/youtu.be link works).",
            ),
        ),
    ]
