# Generated by Django 5.2.8 on 2026-09-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="कोई भी YouTube लिंक चलेगा — Watch, Shorts, Share (?si=...) या Embed लिंक, जो भी कॉपी करें।",
            ),
        ),
    ]
