# Generated by Django 5.2.8 on 2026-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("subject", models.CharField(max_length=160)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Desh Darpan Samvad", max_length=150),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="सच, सरोकार और संवाद", max_length=200
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="branding/")),
                ("favicon", models.ImageField(blank=True, upload_to="branding/")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("primary_phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("telegram_url", models.URLField(blank=True)),
                ("whatsapp_url", models.URLField(blank=True)),
                ("footer_description", models.TextField(blank=True)),
                ("google_analytics_id", models.CharField(blank=True, max_length=60)),
                (
                    "search_console_verification",
                    models.CharField(blank=True, max_length=120),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
