# Generated by Django 5.2.8 on 2026-09-12 16:29

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance / Stringer"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-posted_at"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="advertise_email",
            field=models.EmailField(
                blank=True,
                help_text="Advertising & sponsorship enquiries. Falls back to General email.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="careers_email",
            field=models.EmailField(
                blank=True,
                help_text="Job applications. Falls back to General email.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="editorial_email",
            field=models.EmailField(
                blank=True,
                help_text="Correction requests / editorial queries. Falls back to General email.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="grievance_email",
            field=models.EmailField(
                blank=True,
                help_text="Grievance Officer inbox (IT Rules 2021). Falls back to General email.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="privacy_email",
            field=models.EmailField(
                blank=True,
                help_text="Data access/deletion requests. Falls back to General email.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tips_email",
            field=models.EmailField(
                blank=True,
                help_text="News tips / leads. Falls back to General email.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="General inbox, used as the fallback for every role below.",
                max_length=254,
            ),
        ),
        migrations.CreateModel(
            name="CareerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_applied",
                    models.CharField(
                        blank=True,
                        help_text="Used when no specific opening is selected.",
                        max_length=160,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("cover_note", models.TextField(blank=True)),
                (
                    "resume",
                    models.FileField(
                        upload_to=core.models._resume_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="core.jobopening",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
