# Generated by Django 5.2.8 on 2026-09-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_jobopening_sitesettings_advertise_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobopening",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
    ]
