# Generated by Django 5.2.8 on 2026-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_jobopening_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="investor_email",
            field=models.EmailField(
                blank=True,
                help_text="Investor relations enquiries. Falls back to General email.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="sponsorship_email",
            field=models.EmailField(
                blank=True,
                help_text="Sponsorship / brand partnership enquiries. Falls back to General email.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="advertise_email",
            field=models.EmailField(
                blank=True,
                help_text="Advertising enquiries. Falls back to General email.",
                max_length=254,
            ),
        ),
    ]
