# Generated by Django 5.2.8 on 2026-09-12 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_investor_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EPaperEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edition_date", models.DateField(unique=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "इंदौर संस्करण". Optional.',
                        max_length=160,
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        upload_to="epaper/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="epaper/covers/"),
                ),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-edition_date"],
            },
        ),
    ]
