# Generated by Django 5.2.8 on 2026-09-13 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_epaperedition"),
    ]

    operations = [
        migrations.CreateModel(
            name="EPaperPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="epaper/pages/")),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="core.epaperedition",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "page_number"),
                        name="unique_epaper_page_number",
                    )
                ],
            },
        ),
    ]
