# Generated by Django 5.2.8 on 2026-09-13 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_epaperpage"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="epaperedition",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epaper_editions",
                to="locations.city",
            ),
        ),
        migrations.AlterField(
            model_name="epaperedition",
            name="edition_date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="epaperedition",
            constraint=models.UniqueConstraint(
                fields=("edition_date", "city"),
                name="unique_epaper_edition_per_city_date",
            ),
        ),
    ]
