# Generated by Django 5.2.8 on 2026-09-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_loginotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginotp",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loginotp",
            name="delivery_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loginotp",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loginotp",
            name="user_agent",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="loginotp",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
