# Generated by Django 5.2.8 on 2026-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("ad_type", models.CharField(default="image", max_length=60)),
                ("image", models.ImageField(blank=True, upload_to="ads/")),
                ("desktop_image", models.ImageField(blank=True, upload_to="ads/")),
                ("mobile_image", models.ImageField(blank=True, upload_to="ads/")),
                ("target_url", models.URLField(blank=True)),
                ("html_code", models.TextField(blank=True)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("home_top", "Homepage Top"),
                            ("home_middle", "Homepage Middle"),
                            ("home_bottom", "Homepage Bottom"),
                            ("sidebar", "Sidebar"),
                            ("article_top", "Article Top"),
                            ("article_middle", "Article Middle"),
                            ("article_bottom", "Article Bottom"),
                            ("category_page", "Category Page"),
                            ("mobile", "Mobile"),
                            ("popup", "Popup"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-priority", "-id"],
            },
        ),
    ]
