# Generated by Django 5.2.8 on 2026-08-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="placement",
            field=models.CharField(
                choices=[
                    ("header", "Header"),
                    ("home_top", "Homepage Top"),
                    ("home_middle", "Homepage Middle"),
                    ("home_bottom", "Homepage Bottom"),
                    ("home_video_bottom", "Homepage Video Bottom"),
                    ("sidebar", "Sidebar"),
                    ("article_top", "Article Top"),
                    ("article_middle", "Article Middle"),
                    ("article_bottom", "Article Bottom"),
                    ("category_page", "Category Page"),
                    ("mobile", "Mobile"),
                    ("leaderboard", "Leaderboard"),
                    ("billboard", "Billboard"),
                    ("rectangle", "Rectangle"),
                    ("in_feed", "In Feed"),
                    ("native", "Native"),
                    ("sticky_mobile", "Sticky Mobile"),
                    ("video", "Video"),
                    ("sponsored_content", "Sponsored Content"),
                    ("popup", "Popup"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
