# Generated by Django 5.2.8 on 2026-09-12 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webstories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyslide",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional short vertical video for this slide. When set, it plays instead of the image.",
                upload_to="webstories/slides/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "mov"]
                    )
                ],
            ),
        ),
    ]
